#!/usr/bin/env bash

set -o errexit

DOCKER_REPO_ROOT="/go/src/github.com/coreos/etcd-operator"

docker run --rm \
	-v "$PWD":"$DOCKER_REPO_ROOT" \
	-w "$DOCKER_REPO_ROOT" \
	golang:1.13.4-stretch \
	hack/update_vendor.sh
